# railway.toml
[build]
buildCommand = "composer install --no-dev"

[deploy]
# Perintah ini memberitahu server Apache/Nginx bawaan untuk menggunakan
# folder 'public/' sebagai Document Root.
startCommand = "vendor/bin/heroku-php-apache2 public/"